// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnotraApiDotNet.Dados;

#nullable disable

namespace SnotraApiDotNet.Dados.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230525013346_TesteMudancaPastaMigrations")]
    partial class TesteMudancaPastaMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SnotraApiDotNet.Dados.Modelo.LinkModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("SnotraApiDotNet.Dados.Modelo.NotaModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Caminho");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Texto");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("SnotraApiDotNet.Dados.Modelo.LinkModelo", b =>
                {
                    b.HasOne("SnotraApiDotNet.Dados.Modelo.NotaModelo", "Nota")
                        .WithMany("Urls")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("SnotraApiDotNet.Dados.Modelo.NotaModelo", b =>
                {
                    b.Navigation("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
